-- ==============================================================================
-- PROYECTO: OTOME FLOW
-- Descripción: Esquema completo de Base de Datos para Supabase (PostgreSQL)
-- Tablas, Funciones, Triggers y Políticas de Privacidad (RLS)
-- ==============================================================================

-- ============================================================
-- 1. CREACIÓN DE TABLAS
-- ============================================================

-- Tabla de Perfiles (Extensión de auth.users)
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text,
  role text DEFAULT 'student',
  first_name text,
  last_name text,
  dni text,
  class_name text
);

-- Tabla de Proyectos (Historias creadas por docentes)
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  title text NOT NULL,
  description text,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  project_data jsonb DEFAULT '{}'::jsonb,
  story_data jsonb DEFAULT '{}'::jsonb
);

-- Tabla de Asignaciones (Proyectos asignados a alumnos)
CREATE TABLE public.assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint REFERENCES public.projects ON DELETE CASCADE NOT NULL,
  student_email text NOT NULL,
  assigned_by uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT unique_assignment UNIQUE (project_id, student_email) -- Evita duplicados
);

-- Tabla de Progreso (Telemetría de los intentos de los alumnos)
CREATE TABLE public.student_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  user_email text,
  project_id bigint REFERENCES public.projects ON DELETE CASCADE NOT NULL,
  score int DEFAULT 0,
  time_spent int DEFAULT 0,
  path jsonb DEFAULT '[]'::jsonb,
  completed_at timestamptz DEFAULT now()
);

-- Índice para acelerar las búsquedas de notas en el Dashboard del profesor
CREATE INDEX IF NOT EXISTS idx_progress_project_student ON public.student_progress (project_id, user_email);


-- ============================================================
-- 2. FUNCIONES Y TRIGGERS (Automatización)
-- ============================================================

-- Función para capturar los datos del formulario de registro del HTML
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, first_name, last_name, dni, class_name)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'role', 'student'),
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'dni',
    new.raw_user_meta_data->>'class_name'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger que se dispara cuando un usuario se registra en la plataforma
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ============================================================
-- 3. HABILITAR SEGURIDAD A NIVEL DE FILA (RLS)
-- ============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_progress ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 4. POLÍTICAS DE PRIVACIDAD (POLICIES)
-- ============================================================

-- -------- POLÍTICAS DE PERFILES --------
-- Todos los usuarios logueados pueden ver los perfiles (Necesario para asignar tareas por email)
CREATE POLICY "Permitir lectura de perfiles" ON public.profiles FOR SELECT TO authenticated USING (true);
-- Un usuario solo puede editar su propio perfil
CREATE POLICY "Permitir editar perfil propio" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

-- -------- POLÍTICAS DE PROYECTOS --------
-- SELECT: Ver un proyecto si eres el dueño, O si eres un alumno y te lo han asignado
CREATE POLICY "Ver proyectos propios o asignados" ON public.projects FOR SELECT TO authenticated 
USING (
  auth.uid() = user_id 
  OR 
  id IN (SELECT project_id FROM public.assignments WHERE student_email = (SELECT email FROM auth.users WHERE id = auth.uid()))
);

-- INSERT: Cualquiera puede crear un proyecto (Incluso asignándoselo a otro profesor en la función "Compartir")
CREATE POLICY "Permitir crear y compartir proyectos" ON public.projects FOR INSERT TO authenticated WITH CHECK (true);

-- UPDATE/DELETE: Solo el profesor dueño del proyecto puede editarlo o borrarlo
CREATE POLICY "Solo dueños pueden editar" ON public.projects FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Solo dueños pueden borrar" ON public.projects FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- -------- POLÍTICAS DE ASIGNACIONES --------
-- Los profesores ven lo que asignaron, los alumnos ven lo que reciben
CREATE POLICY "View assignments" ON public.assignments FOR SELECT TO authenticated 
USING (student_email = (SELECT email FROM auth.users WHERE id = auth.uid()) OR assigned_by = auth.uid());
-- Solo los profesores pueden asignar o borrar asignaciones
CREATE POLICY "Teachers can assign" ON public.assignments FOR INSERT TO authenticated WITH CHECK (auth.uid() = assigned_by);
CREATE POLICY "Teachers can delete assigns" ON public.assignments FOR DELETE TO authenticated USING (auth.uid() = assigned_by);

-- -------- POLÍTICAS DE PROGRESO (NOTAS) --------
-- Privacidad Estricta de Lectura: Solo lee el alumno que hizo el examen, o el profesor creador del proyecto
CREATE POLICY "Privacidad estricta de notas" ON public.student_progress FOR SELECT TO authenticated 
USING (
  auth.uid() = user_id 
  OR 
  EXISTS (SELECT 1 FROM public.projects WHERE public.projects.id = student_progress.project_id AND public.projects.user_id = auth.uid())
);
-- Los alumnos insertan sus propias notas
CREATE POLICY "Permitir guardar progreso propio" ON public.student_progress FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Profesores pueden borrar notas al borrar proyecto" ON public.student_progress FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM public.projects WHERE public.projects.id = student_progress.project_id AND public.projects.user_id = auth.uid())
);

-- ============================================================
-- NOTA SOBRE STORAGE (ALMACENAMIENTO DE IMÁGENES)
-- ============================================================
/*
  Las políticas de Storage no se pueden definir directamente en este script sin acceso de superusuario.
  Para que la plataforma funcione en un entorno nuevo, es necesario crear manualmente en Supabase:
  1. Un Bucket público llamado: 'otome-assets'
  2. Aplicar una política RLS al bucket que permita a los usuarios autenticados realizar operaciones 
     (SELECT, INSERT, UPDATE, DELETE).
*/